Update required status checks (#140)

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -8,8 +8,6 @@ on:
     branches: [ main, dev ]
   pull_request:
     branches: [ main, dev ]
-    # Add assigned to defaults as a hack to easily trigger code-gen PRs to run validation
-    types: [assigned, opened, synchronize, reopened]
 
 defaults:
   run:
@@ -49,3 +47,17 @@ jobs:
     - name: Run static analysis
       run: |
         vendor/bin/phpstan analyse --memory-limit=500M --error-format=github
+
+  # The check-php-version-matrix returns success if all matrix jobs in build are successful; otherwise, it returns a failure.
+  # Use this as a PR status check for GitHub Policy Service instead of individual matrix entry checks.
+  check-php-version-matrix:
+    runs-on: ubuntu-latest
+    needs: validate-pull-request
+    if: always()
+    steps:
+      - name: All build matrix options are successful
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: One or more build matrix options failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
